const STATUS = {
  CREATED: "CREATED",
  APPLIED: "APPLIED",
  REJECTED: "REJECTED",
  NO_RESPONSE: "NO_RESPONSE",
  NO_LONGER_INTERESTED: "NO_LONGER_INTERESTED",
  INTERVIEW_ROUND_1: "INTERVIEW_ROUND_1",
  INTERVIEW_ROUND_2: "INTERVIEW_ROUND_2",
  INTERVIEW_ROUND_3: "INTERVIEW_ROUND_3",
  INTERVIEW_ROUND_4: "INTERVIEW_ROUND_4",
  INTERVIEW_ROUND_5: "INTERVIEW_ROUND_5",
  INTERVIEW_ROUND_6: "INTERVIEW_ROUND_6",
  INTERVIEW_ROUND_7: "INTERVIEW_ROUND_7",
  INTERVIEW_ROUND_8: "INTERVIEW_ROUND_8",
  INTERVIEW_ROUND_9: "INTERVIEW_ROUND_9",
  INTERVIEW_ROUND_10: "INTERVIEW_ROUND_10",
  OFFER: "OFFER",
  NEGOTIATING: "NEGOTIATING",
  ACCEPTED: "ACCEPTED"
};

export { STATUS };
